Added a new class EmbedList
chrisdewa/dpytools pull request #7
Opened 2021-05-30 07:36 UTC by Kshitiz-Arya

It takes a dictionary containing name and values as key value pair and split them into several embeds according to size provided by the user.

2021-05-30 13:41 UTC, chrisdewa commented
Thanks for the PR, I'll review it soon!

2021-05-30 13:51 UTC, Kshitiz-Arya commented
I have not tested this for edge cases, so it is ok if you can test them first.

2021-05-30 17:11 UTC, chrisdewa requested changes
I like where his class is heading but its missing some important features. 
Also, i think what this class provide is an easy way to paginate multiple fields into whatever amount of embeds needed. Perpahs it'd be better if the class used what the base Embed subclass, provided in this library, can do and expanded it with the pagination.

Please address them for futher review.

2021-05-30 17:11 UTC, chrisdewa commented on dpytools/embeds.py
> +    """A class that takes dictionary containing name and value and splint them into several Embeds.
If this class only really focuses on paginating fields, perhaps its better to change its name and description to that.

2021-05-30 17:11 UTC, chrisdewa commented on dpytools/embeds.py
> +            dicts :- Name, Value dictionary to generate embed from
It's improtant to specify that name and value correspond to each field's key and value.

2021-05-30 17:11 UTC, chrisdewa commented on dpytools/embeds.py
> +        for d in self._chunks(dicts):
Same as before, variable names in this loop are too ambiguous. Try to name them something that actually tells what they are or what they do

2021-05-30 17:11 UTC, chrisdewa commented on dpytools/embeds.py
> +class EmbedList:
Overall i like where this class is heading but i thing it's missing some important things. For example, author url and icon_url, or the embed url, etc. The class should be able to make a full Embed. 

A suggestion could be accepting a `base_embed` argument on `__init__` that contains everyting but the fields and just paginate the fields using the base embed as template.

2021-06-03 09:31 UTC, Kshitiz-Arya commented
I have made few changes to to implementation of EmbedList, which has been renamed to PaginatedEmbeds (I am bad at naming things so feel free to make any changes here)

2021-06-03 09:44 UTC, Kshitiz-Arya commented on dpytools/embeds.py
> +    def __init__(self, embed:Embed, fields_dict:Dict[str, str],size:int=25, inline:bool=True):
Now taking an user-initialized embed to act as a template for paginated embed

2021-06-03 09:46 UTC, Kshitiz-Arya commented on dpytools/embeds.py
> +        self.clear()
Made this change

2021-06-04 13:09 UTC, chrisdewa commented
Thanks for the corrections! I review this today, i hope, i just ask that you pull the lastest changes from master so there's no conflicts with the PR!

2021-06-04 15:30 UTC, merged

2021-06-04 15:30 UTC, chrisdewa commented
Finally merging!